###
POST http://localhost:8080/test-insertion/save-concurrent-and-atomic-by-transaction-id-another-table/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update-by-session/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-by-spring-with-async/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring/2
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update/10
Content-Type: application/json
