POST http://localhost:8080/test-insertion/save-concurrent-and-atomic-by-transaction-id/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-concurrent-and-atomic/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-array-after-insert/20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-by-transaction-id/98f0cc67-5326-4eeb-9836-eecede946ccd
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-transaction-id/2?countRow=20000
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-array/4
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read-unnest/8
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/set-ready-to-read/5
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update-by-session/10
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/save-by-spring-with-async/20000
Content-Type: application/json
###
POST http://localhost:8080/test-insertion/spring/2
Content-Type: application/json

###
POST http://localhost:8080/test-insertion/spring-update/10
Content-Type: application/json
