CREATE TABLE ACTIVE_TRANSACTION
(
    ID bigint NOT NULL,
    transaction_id uuid NOT NULL
);
ALTER TABLE ACTIVE_TRANSACTION ADD CONSTRAINT PK_ACTIVE_TRANSACTION PRIMARY KEY (ID);
CREATE INDEX IX_ACTIVE_TRANSACTION_transaction_id on ACTIVE_TRANSACTION (transaction_id);